{{- $virtualhost := index (pick .Values.Project.virtualhost .EnvFiles.Config.ENV) .EnvFiles.Config.ENV -}}
version: '3.3'


services:


  proxy:
    image: traefik:1.4.0-alpine
    container_name: kickoff-proxy
    restart: {{ if and (ne "local" .EnvFiles.Config.ENV) (eq false .Values.Modules.graylog.enable) }}unless-stopped{{ else }}"no"{{ end }}
    command: --docker --logLevel={{ .EnvFiles.Config.TRAEFIK_LOG_LEVEL }}
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    labels:
      - traefik.frontend.rule=Host:traefik.{{ $virtualhost }}
      - traefik.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml:ro
      {{- if eq "local" .EnvFiles.Config.ENV }}
      - ../toolbox/generated/traefik/certs:/certs:ro
      {{- else }}
      - {{ .EnvFiles.Config.TRAEFIK_CERT_FILE_PATH }}:/certs/{{ $virtualhost }}.crt:ro
      - {{ .EnvFiles.Config.TRAEFIK_KEY_FILE_PATH }}:/certs/{{ $virtualhost }}.key:ro
      - ../toolbox/generated/traefik/auth/:/auth/:ro
      {{ end }}


networks:


  proxy:
    driver: bridge