# Entry points definition
defaultEntryPoints = ["http", "https"]

[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]
[[entryPoints.https.tls.certificates]]
{{- if eq "local" .EnvFiles.Kickoff.ENV }}
certFile = "tests/{{ .Values.Kickoff.project.virtualhost.local }}.crt"
keyFile = "tests/{{ .Values.Kickoff.project.virtualhost.local }}.key"
{{- else }}
{{- range $env, $virtualhost := .Values.Kickoff.project.virtualhost }}
{{- if eq $env $.EnvFiles.Kickoff.ENV }}
certFile = "certs/{{ $virtualhost }}.crt"
keyFile = "certs/{{ $virtualhost }}.key"
{{- end }}
{{- end }}
{{ end }}

# API backend
[web]
address = ":8080"
{{- if ne "local" .EnvFiles.Kickoff.ENV }}
[web.auth.digest]
usersFile = "auth/.htdigest"
{{- end }}