version: '3.3'


services:


  graylog-mongo:
    image: mongo:3.4.7
    container_name: {{ .EnvFiles.Kickoff.ENV }}-{{ .Values.Kickoff.project.name }}-graylog-mongo
    restart: {{ if ne "local" .EnvFiles.Kickoff.ENV }}unless-stopped{{ else }}"no"{{ end }}
    networks:
      - backend
    labels:
      - traefik.enable=false
    volumes:
      - graylog_mongo_data:/data/db


  graylog-elasticsearch:
    image: elasticsearch:2.4.5-alpine
    container_name: {{ .EnvFiles.Kickoff.ENV }}-{{ .Values.Kickoff.project.name }}-graylog-elasticsearch
    restart: {{ if ne "local" .EnvFiles.Kickoff.ENV }}unless-stopped{{ else }}"no"{{ end }}
    command: elasticsearch -Des.cluster.name='graylog'
    networks:
      - backend
    environment:
      - ES_JAVA_OPTS={{ .EnvFiles.Kickoff.GRAYLOG_ES_JAVA_OPTS }}
    labels:
      - traefik.enable=false
    volumes:
      - graylog_elasticsearch_data:/usr/share/elasticsearch/data


  graylog-server:
    image: graylog2/server:2.3.0-1
    container_name: {{ .EnvFiles.Kickoff.ENV }}-{{ .Values.Kickoff.project.name }}-graylog
    restart: {{ if ne "local" .EnvFiles.Kickoff.ENV }}unless-stopped{{ else }}"no"{{ end }}
    networks:
      - proxy
      - backend
    ports:
      - "12201:12201/udp"
    environment:
      - GRAYLOG_ROOT_USERNAME={{ .Values.Kickoff.graylog.user }}
      {{- range $env, $virtualhost := .Values.Kickoff.project.virtualhost }}
      {{- if eq $env $.EnvFiles.Kickoff.ENV }}
      - GRAYLOG_WEB_ENDPOINT_URI=https://graylog.{{ $virtualhost }}/api/
      {{- end }}
      {{- end }}
      - GRAYLOG_MONGODB_URI=mongodb://graylog-mongo/graylog
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://graylog-elasticsearch:9200
      - GRAYLOG_CONTENT_PACKS_AUTO_LOAD=udp-input.json
      - GRAYLOG_CONTENT_PACKS_LOADER_ENABLED=true
      - GRAYLOG_CONTENT_PACKS_DIR=data/contentpacks
      - GRAYLOG_SERVER_JAVA_OPTS={{ .EnvFiles.Kickoff.GRAYLOG_SERVER_JAVA_OPTS }}
    env_file: ./toolbox/generated/graylog/.env
    labels:
      - traefik.backend={{ .EnvFiles.Kickoff.ENV }}-{{ .Values.Kickoff.project.name }}-graylog
      {{- range $env, $virtualhost := .Values.Kickoff.project.virtualhost }}
      {{- if eq $env $.EnvFiles.Kickoff.ENV }}
      - traefik.frontend.rule=Host:graylog.{{ $virtualhost }}
      {{- end }}
      {{- end }}
      - traefik.port=9000
      - traefik.docker.network=kickoff_proxy
    volumes:
      - graylog_server_data:/usr/share/graylog/data/journal
      - ./graylog/udp-input.json:/usr/share/graylog/data/contentpacks/udp-input.json:ro


volumes:


  graylog_mongo_data:
    driver: local


  graylog_elasticsearch_data:
    driver: local


  graylog_server_data:
    driver: local


networks:


  proxy:
    external:
      name: kickoff_proxy


  backend:
    external:
      name: {{ .EnvFiles.Kickoff.ENV }}{{ .Values.Kickoff.project.name }}_backend