{{- $virtualhost := index (pick .Orbit.Project.virtualhost .Orbit.EnvFile.ENV) .Orbit.EnvFile.ENV -}}
version: '3.3'


services:


  nginx:
    build:
      context: .
      args:
        - UID={{ if ne "windows" os }}${UID}{{ else }}82{{ end }}
    container_name: {{ .Orbit.EnvFile.ENV }}-{{ .Orbit.Project.name }}-nginx
    restart: {{ if and (ne "local" .Orbit.EnvFile.ENV) (eq false .Orbit.Modules.graylog.enable) }}unless-stopped{{ else }}"no"{{ end }}
    labels:
      - traefik.backend={{ .Orbit.EnvFile.ENV }}-{{ .Orbit.Project.name }}-nginx
      {{- if eq "true" .Orbit.EnvFile.TRAEFIK_PREFIX }}
      - traefik.frontend.rule=Host:{{ .Orbit.EnvFile.ENV }}.{{ $virtualhost }},www-{{ .Orbit.EnvFile.ENV }}.{{ $virtualhost }}
      {{- else }}
      - traefik.frontend.rule=Host:{{ $virtualhost }},www.{{ $virtualhost }}
      {{- end }}
      - traefik.docker.network=kickoff_proxy
    networks:
      - proxy
      - backend
    volumes:
      {{- if eq "true" .Orbit.EnvFile.ENABLE_DOCKER_SYNC }}
      - {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }}_sync_app:/var/www/html:nocopy
      {{- else }}
      - ../../{{ .Orbit.EnvFile.DIR }}:/var/www/html:{{ if eq "darwin" os }}cached{{ else }}ro{{ end }}
      {{- end }}
      - ./conf.d/php-fpm.conf:/etc/nginx/conf.d/php-fpm.conf:ro
    {{- if eq true .Orbit.Modules.graylog.enable }}
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:{{ .Orbit.EnvFile.GRAYLOG_PORT }}
    {{ end }}

networks:


  proxy:
    external:
      name: kickoff_proxy


  backend:
    external:
      name: {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }}_backend

{{ if eq "true" .Orbit.EnvFile.ENABLE_DOCKER_SYNC }}
volumes:


  {{ .Orbit.EnvFile.ENV }}{{ .Orbit.Project.name }}_sync_app:
    external: true
{{- end }}